trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - deploy/Occurrences.Infrastructure.Persistence.Migrations/*

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/Occurrences.Infrastructure.Persistence'
  name: 5.$(Year:yy).$(DayOfYear)$(Rev:.rr)
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'  

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
        name: Hosted Windows 2019 with VS2019
        demands: msbuild

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: |
          $(workingDirectory)/*.csproj
        feedsToUse: config
        nugetConfigPath: .nuget/NuGet.config

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test
        projects: |
          $(workingDirectory)/*.csproj

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        projects: |
          $(workingDirectory)/*.csproj
        arguments: '--output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
        name: Hosted Windows 2019 with VS2019
        demands: msbuild

    strategy:
      runOnce:
        deploy:
          steps:
          - task: BatchScript@1
            inputs:
              filename: '$(workingDirectory)/EF-Database-Update.cmd'
              arguments: '--connectionString $(ConnectionString)'