
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - src/Shared.Abstractions/*
    - src/Shared.Extensions/*
    - src/Shared.Extensions.Mvc/*
    - src/Shared.Specs/*

variables:
  sourceDirectory: '$(System.DefaultWorkingDirectory)/src/Shared.*'
  name: 5.$(Year:yy).$(DayOfYear)$(Rev:.rr)
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'  

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
        name: Hosted Windows 2019 with VS2019
        demands: msbuild

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: |
          $(sourceDirectory)/*.csproj
        feedsToUse: config
        nugetConfigPath: .nuget/NuGet.config

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(sourceDirectory)/*.csproj
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test
        projects: |
          $(sourceDirectory)/*.csproj

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: pack
        projects: |
          $(sourceDirectory)/Shared.Abstractions.csproj
          $(sourceDirectory)/Shared.Extensions.csproj
          $(sourceDirectory)/Shared.Extensions.Mvc.csproj
          $(sourceDirectory)/Shared.Specs.csproj
        arguments: '--output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
        name: Hosted Windows 2019 with VS2019
        demands: msbuild

    strategy:
      runOnce:
        deploy:
          steps:          
          - task: NuGetCommand@2
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '525a0dbd-3d6d-4f62-aba4-f4d004295d7d'
              allowPackageConflicts: true
