
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - src/Occurrences.Domain.Models/*
    - src/Occurrences.Infrastructure.Persistence/*
    - deploy/Occurrences.Infrastructure.Persistence.Migrations/*

variables:
- group: Development
- name: sourceDirectory
  value: '$(System.DefaultWorkingDirectory)/deploy/Occurrences.Infrastructure.Persistence.Migrations'
- name: artifactDirectory
  value: '$(Build.ArtifactStagingDirectory)/../drop/deploy/Occurrences.Infrastructure.Persistence.Migrations'
- name: buildConfiguration
  value: 'Release'  
- name: MSBUILDSINGLELOADCONTEXT
  value: 1

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
        name: Hosted Windows 2019 with VS2019
        demands: msbuild

    steps:
    - task: PowerShell@2
      displayName: 'Set-Version'
      inputs:
        filePath: 'deploy/Shared.Deploy/Assembly/Set-Version.ps1'
        arguments: '-Path $(System.DefaultWorkingDirectory) -VersionToReplace 5.20.1 -Major 05'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: DeleteFiles@1
      displayName: 'Delete unwanted projects'
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)
        RemoveSourceFolder: true
        contents: |
          /docs/*
          /samples/*
          /tests/*

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: |
          $(sourceDirectory)/*.csproj
        feedsToUse: config
        nugetConfigPath: .nuget/NuGet.config

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(sourceDirectory)/*.csproj
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test
        projects: |
          $(System.DefaultWorkingDirectory)/**/*.Specs.Unit.csproj
          
    - task: CopyFiles@2
      displayName: 'Copy deploy'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/deploy'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/deploy'
        OverWrite: true

    - task: CopyFiles@2
      displayName: 'Copy src'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/src'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/src'
        OverWrite: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
        name: Hosted Windows 2019 with VS2019
        demands: msbuild

    strategy:
      runOnce:
        deploy:
          steps:
          - task: BatchScript@1
            inputs:
              workingFolder: $(artifactDirectory)
              filename: '$(artifactDirectory)/EF-Database-Update.cmd "$(StackSqlConnection)"'
              arguments: '$(ConnectionString)'