
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - tests/*

variables:
- group: Development
- name: sourceDirectory
  value: '$(System.DefaultWorkingDirectory)/tests'
- name: artifactDirectory
  value: '$(Build.ArtifactStagingDirectory)/../drop'
- name: buildConfiguration
  value: 'Release'
- name: MSBUILDSINGLELOADCONTEXT
  value: 1

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
        name: Hosted Windows 2019 with VS2019
        demands: msbuild

    steps:
    - task: PowerShell@2
      displayName: 'Set-Version'
      inputs:
        filePath: 'deploy/Shared.Deploy/Assembly/Set-Version.ps1'
        arguments: '-Path $(System.DefaultWorkingDirectory) -VersionToReplace 5.20.1 -Major 05'
        workingDirectory: '$(sourceDirectory)'

    - task: DeleteFiles@1
      displayName: 'Delete unwanted projects'
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)
        RemoveSourceFolder: true
        contents: |
          /docs/*
          /deploy/*
          /samples/*
          /src/*

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: |
          $(sourceDirectory)/**/*.csproj
        feedsToUse: config
        nugetConfigPath: .nuget/NuGet.config

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(sourceDirectory)/**/*.csproj
        arguments: '--configuration $(BuildConfiguration)'

    - task: CmdLine@2
      inputs:
        script: |
          cd /
          cd $(sourceDirectory)
          dotnet test

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
        name: Hosted Windows 2019 with VS2019
        demands: msbuild

    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: 'echo Publish report to Dev build report location. Releases will publish to production release folder.'