trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - src/Subjects.Domain.Models/*
    - src/Subjects.Presentation.Functions/*
    - src/Shared.Abstractions/*
    - src/Shared.Extensions/*
    - src/Shared.Extensions.Mvc/*
    - src/Shared.Specs/*

variables:
- group: Development
- name: functionAppName
  value: 'subject-functions'
- name: sourceDirectory
  value: '$(System.DefaultWorkingDirectory)/src/Subjects.Presentation.Functions'
- name: testDirectory
  value: '$(System.DefaultWorkingDirectory)/src/Subjects.Specs.Unit'
- name: buildConfiguration
  value: 'Release'  
- name: MSBUILDSINGLELOADCONTEXT
  value: 1

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
        name: Hosted Windows 2019 with VS2019

    steps:
    - task: PowerShell@2
      displayName: 'Set-Version'
      inputs:
        filePath: 'deploy/Shared.Deploy/Assembly/Set-Version.ps1'
        arguments: '-Path $(System.DefaultWorkingDirectory) -VersionToReplace 5.20.1 -Major 05'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: DeleteFiles@1
      displayName: 'Delete unwanted projects'
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)
        RemoveSourceFolder: true
        contents: |
          /docs/*
          /deploy/*
          /samples/*
          /tests/*

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '$(sourceDirectory)/*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: $(sourceDirectory)/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    - task: DotNetCoreCLI@2
      displayName: 'Test'
      continueOnError: true
      inputs:
        command: test
        projects: '$(testDirectory)/*.csproj'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop